---
- name: become root and install redis with ssl support
  ansible.builtin.import_tasks: root.yml
  become: true
  tags: srv_redis_all

- name: flush handlers
  ansible.builtin.meta: flush_handlers
  tags: srv_redis_all
...
