---
- name: add redis ppa repository from chris lea
  ansible.builtin.apt_repository:
    repo: ppa:chris-lea/redis-server
    codename: "{{ ansible_lsb.codename }}"
    filename: redis
    mode: 0644
    update_cache: true
  register: _add_redis_ppa
  until: _add_redis_ppa is successful

- name: install redis and stunnel packages
  ansible.builtin.apt:
    name:
      - redis-server
      - redis-tools
      - stunnel4
      - ssl-cert  # for snakeoil certificate


- name: backup vanilla redis configuration
  ansible.builtin.command:
    cmd: cp -a /etc/redis/redis.conf /etc/redis/redis.conf.orig
    creates: /etc/redis/redis.conf.orig

- name: ansible comment in redis.conf
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    line: "# ansible-managed"
    insertbefore: BOF

- name: tweak redis parameters
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^#?\s*{{ item.key }}\s'
    line: "{{ item.key }} {{ item.value }}"
  with_dict: "{{ redis_parameters }}"
  loop_control:
    label: "{{ item.key }}"
  notify: restart redis service

- name: set redis password
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^#?\s*requirepass\s'
    line: "requirepass {{ redis_password }}"
    owner: redis
    group: redis
    mode: 0640
  when:
    - redis_password is defined
    - redis_password is not none
    - redis_password != ''  # noqa 602
  no_log: "{{ hide_secrets |bool }}"
  notify: restart redis service

- name: disable redis password
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^#?\s*requirepass\s'
    line: "#requirepass foobar"
    owner: redis
    group: redis
    mode: 0640
  when: redis_password is not defined
        or redis_password is none
        or redis_password == ''  # noqa 602
  no_log: true
  notify: restart redis service


- name: verify that redis ssl certificate and key are readable
  ansible.builtin.file:
    path: "{{ item }}"
    state: file
  loop:
    - "{{ redis_ssl_cert }}"
    - "{{ redis_ssl_key }}"

- name: ensure that private key is readable by redis stunnel not world
  ansible.builtin.file:
    path: "{{ redis_ssl_key }}"
    state: file
    group: "{{ certbot_group |d('ssl-cert') }}"
    mode: 'o='

- name: ensure that redis stunnel can accces private key directory
  ansible.builtin.file:
    path: "{{ redis_ssl_key |dirname }}"
    state: directory
    group: "{{ certbot_group |d('ssl-cert') }}"
    mode: g+rx


- name: configure stunnel for redis server
  ansible.builtin.template:
    src: redis-stunnel.conf
    dest: /etc/redis/stunnel.conf
    owner: root
    group: root
    mode: 0644

- name: setup stunnel ssl service for redis server
  ansible.builtin.template:
    src: redis-stunnel.service
    dest: /etc/systemd/system/redis-stunnel.service
    owner: root
    group: root
    mode: 0644
  register: _redis_stunnel_systemd_unit
  notify: restart redis stunnel service


- name: enable redis and stunnel ssl services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: "{{ _redis_stunnel_systemd_unit is changed }}"
  loop:
    - redis-server
    - redis-stunnel


- name: open redis ports in ufw
  community.general.ufw:
    rule: allow
    port: "{{ item |string }}"
    proto: tcp
  no_log: "{{ hide_secrets |bool }}"
  loop: "{{ redis_open_ports }}"
  when: lin_firewall == 'ufw'

- name: open redis ports in ferm
  ivansible.base.ferm_port:
    port: "{{ redis_open_ports }}"
    proto: tcp
    zone: external
    comment: redis
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'

- name: open redis insecure port internally in ferm
  ivansible.base.ferm_port:
    port: "{{ redis_port_tcp }}"
    proto: tcp
    zone: internal
    comment: redis
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'


- name: enable/disable compression of redis/stunnel logs
  ansible.builtin.replace:
    path: "/etc/logrotate.d/{{ item }}"
    regexp: "{{ lookbehind }}(compress|delaycompress)"
    replace: "{{ commentout }}\\1"
  vars:
    lookbehind: "{{ lin_compress_logs |bool |ternary('(?:#\\s*)','(?<!#)') }}"
    commentout: "{{ lin_compress_logs |bool |ternary('','#') }}"
  loop:
    - redis-server
    - stunnel4
  when: lin_compress_logs is not none
...
