---
namespace: ivansible
name: server
version: 1.0.0

description: Ansible collection for Databases and server software

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  - linux
  - server
  - monitoring
  - database
  - postgresql
  - mongodb
  - redis
  - nxserver
  - cloudflare
  - netdata
  - tor
  - vpn
  - dante
  - ziproxy

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/server
documentation: https://github.com/ivansible/server
homepage: https://github.com/ivansible/server
issues: https://github.com/ivansible/server/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
