---
namespace: claranet
name: server
version: 1.0.1

description: Ansible collection for Databases and server software

authors:
  - Ivan Andreev <ivandeex@gmail.com>
  - Jérôme Respaut <jerome.respaut@fr.clara.net>

tags:
  - linux
  - server
  - monitoring
  - database
  - postgresql
  - mongodb
  - redis
  - nxserver
  - cloudflare
  - netdata
  - tor
  - vpn
  - dante
  - ziproxy

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/claranet/server
documentation: https://github.com/claranet/server
homepage: https://github.com/claranet/server
issues: https://github.com/claranet/server/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
