---
## handlers for ivansible.server.mongodb
## inherited from ivansible.linux.base:
## - reload systemd daemon

- name: restore mongodb authorization
  ansible.builtin.lineinfile:
    path: /etc/mongod.conf
    regexp: '^(\s+)authorization:'
    line: '\g<1>authorization: enabled'
    backrefs: true
  become: true

- name: restart mongodb service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
  become: true
...
