---
## handlers for ivansible.server.redis

- name: restart redis service
  ansible.builtin.systemd:
    name: redis-server
    state: restarted
  become: true

- name: restart redis stunnel service
  ansible.builtin.systemd:
    name: redis-stunnel
    state: restarted
  become: true
...
