---
- name: install haveged (entropy service)
  ansible.builtin.apt:
    name:
      - haveged
      - rng-tools

- name: enable entropy services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - haveged
    - rng-tools
...
