---
- name: become root and deploy dante
  ansible.builtin.import_tasks: root.yml
  become: true
  when: dante_enable |bool
  tags: srv_dante_all

- name: flush handlers
  ansible.builtin.meta: flush_handlers
  tags: srv_dante_all
...
