---
## handlers for ivansible.server.tor

- name: restart tor service
  ansible.builtin.systemd:
    name: tor
    state: restarted
  become: true

- name: restart privoxy service
  ansible.builtin.systemd:
    name: privoxy
    state: restarted
  become: true
...
