---
## handlers for ivansible.server.sshtun
## note: "restart ssh service" is inherited from role ivansible.base.linux

- name: restart sshtun service
  ansible.builtin.systemd:
    name: sshtun-serv
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
...
