---
- name: install tor
  ansible.builtin.include_tasks: "install-{{ method }}.yml"
  args:
    apply:
      become: true
      tags: lin_tor_install
  vars:
    method: "{{ tor_from_universe |bool |ternary('universe', 'official') }}"
  tags: lin_tor_install

- name: activate tor service
  ansible.builtin.systemd:
    name: tor
    state: started
    enabled: true
  tags: lin_tor_service

- name: configure tor
  ansible.builtin.import_tasks: config.yml
  tags: lin_tor_config

- name: setup privoxy
  ansible.builtin.import_tasks: privoxy.yml
  when: tor_privoxy_enable |bool
  tags: lin_tor_privoxy
...
