---
## handlers for ivansible.server.netdata

- name: restart netdata service
  ansible.builtin.systemd:
    name: netdata
    state: restarted
    enabled: true
  become: true

- name: reload netdata alarms
  ansible.builtin.command: killall -USR2 netdata
  become: true
...
