---
- name: become root and deploy sshtun service
  ansible.builtin.import_tasks: root.yml
  become: true
  when: srv_sshtun_ssh_user |default('')
  tags: srv_sshtun_all

- name: run handlers now
  ansible.builtin.meta: flush_handlers
...
