---
- name: most steps require elevated privileges
  ansible.builtin.import_tasks: root.yml
  become: true
  tags:
    - lin_nx_root
    - lin_nx_all

- name: authorize user
  ansible.builtin.import_tasks: user.yml
  become: false
  tags:
    - lin_nx_user
    - lin_nx_all

- name: reboot to work around dbus issues
  ansible.builtin.import_tasks: reboot.yml
  become: true
  when:
    - nx_nxserver_packages |d({}) is changed
    - nx_desktop_packages |d({}) is changed
  tags:
    - lin_nx_reboot
    - lin_nx_all
...
