---
all:
  children:
    molecule:
      children:
        docker_molecule:
          vars:
            ansible_user: ansible
        local_molecule:
      vars:
        is_permitted: false
        allow_sysctl: false
        lin_use_ssh: false
        lin_firewall: none
        lin_core_time_sync: false
        lin_core_system_locale: en_US.UTF-8

        ## run test on internal port with random password
        redis_port_tcp: 55379
        redis_port_ssl: 55389
        redis_password: "{{ lookup('password', '/tmp/testpass chars=ascii_letters') }}"
...
